/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CryptoPunks2Minter__factory } from "./CryptoPunks2Minter__factory";
export { IERC721Delegate__factory } from "./IERC721Delegate__factory";
