nodeLinker: node-modules

packageExtensions:
  hardhat-watcher@*:
    peerDependenciesMeta:
      hardhat:
        optional: true
  '@parcel/workers@*':
    dependencies:
      '@parcel/core': '*'
  '@parcel/fs@*':
    dependencies:
      '@parcel/core': '*'
  '@parcel/cache@*':
    dependencies:
      '@parcel/core': '*'
  '@parcel/package-manager@*':
    dependencies:
      '@parcel/core': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
