/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as atkDelegateSol from "./ATKDelegate.sol";
export { IATKLand__factory } from "./IATKLand__factory";
