/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IStargateRouter {
  export type LzTxObjStruct = {
    dstGasForCall: PromiseOrValue<BigNumberish>;
    dstNativeAmount: PromiseOrValue<BigNumberish>;
    dstNativeAddr: PromiseOrValue<BytesLike>;
  };

  export type LzTxObjStructOutput = [BigNumber, BigNumber, string] & {
    dstGasForCall: BigNumber;
    dstNativeAmount: BigNumber;
    dstNativeAddr: string;
  };
}

export declare namespace Types {
  export type ICallStruct = {
    _to: PromiseOrValue<string>;
    _value: PromiseOrValue<BigNumberish>;
    _calldata: PromiseOrValue<BytesLike>;
  };

  export type ICallStructOutput = [string, BigNumber, string] & {
    _to: string;
    _value: BigNumber;
    _calldata: string;
  };
}

export declare namespace IMultichainPortal {
  export type StargateArgsStruct = {
    dstChainId: PromiseOrValue<BigNumberish>;
    srcPoolId: PromiseOrValue<BigNumberish>;
    dstPoolId: PromiseOrValue<BigNumberish>;
    minAmountOut: PromiseOrValue<BigNumberish>;
    lzTxObj: IStargateRouter.LzTxObjStruct;
    receiver: PromiseOrValue<string>;
    data: PromiseOrValue<BytesLike>;
  };

  export type StargateArgsStructOutput = [
    number,
    number,
    number,
    BigNumber,
    IStargateRouter.LzTxObjStructOutput,
    string,
    string
  ] & {
    dstChainId: number;
    srcPoolId: number;
    dstPoolId: number;
    minAmountOut: BigNumber;
    lzTxObj: IStargateRouter.LzTxObjStructOutput;
    receiver: string;
    data: string;
  };
}

export interface MultichainPortalInterface extends utils.Interface {
  functions: {
    "beneficiary()": FunctionFragment;
    "fee()": FunctionFragment;
    "initialize(address,address,address,address,uint256)": FunctionFragment;
    "lastChainId()": FunctionFragment;
    "lastErr()": FunctionFragment;
    "lastNonce()": FunctionFragment;
    "lastSrcAddress()": FunctionFragment;
    "mulDiv(uint256,uint256,uint256)": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "portalRouter()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "send(uint256,uint16,uint16,uint16,uint256,(uint256,uint256,bytes),address,bytes)": FunctionFragment;
    "sgReceive(uint16,bytes,uint256,address,uint256,bytes)": FunctionFragment;
    "stargateRouter()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "swapERC20AndCall(address,address,uint256,address,address,bytes,(address,uint256,bytes)[])": FunctionFragment;
    "swapERC20AndSend(uint256,uint256,address,address,address,bytes,(uint16,uint16,uint16,uint256,(uint256,uint256,bytes),address,bytes))": FunctionFragment;
    "swapNativeAndCall(address,address,address,bytes,(address,uint256,bytes)[])": FunctionFragment;
    "swapNativeAndSend(uint256,uint256,uint256,address,address,bytes,(uint16,uint16,uint16,uint256,(uint256,uint256,bytes),address,bytes))": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "usdc()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "beneficiary"
      | "fee"
      | "initialize"
      | "lastChainId"
      | "lastErr"
      | "lastNonce"
      | "lastSrcAddress"
      | "mulDiv"
      | "onERC1155BatchReceived"
      | "onERC1155Received"
      | "onERC721Received"
      | "owner"
      | "pause"
      | "paused"
      | "portalRouter"
      | "renounceOwnership"
      | "send"
      | "sgReceive"
      | "stargateRouter"
      | "supportsInterface"
      | "swapERC20AndCall"
      | "swapERC20AndSend"
      | "swapNativeAndCall"
      | "swapNativeAndSend"
      | "transferOwnership"
      | "unpause"
      | "usdc"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "beneficiary",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lastChainId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastErr", values?: undefined): string;
  encodeFunctionData(functionFragment: "lastNonce", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastSrcAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mulDiv",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "portalRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      IStargateRouter.LzTxObjStruct,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sgReceive",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "stargateRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "swapERC20AndCall",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      Types.ICallStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapERC20AndSend",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      IMultichainPortal.StargateArgsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapNativeAndCall",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      Types.ICallStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapNativeAndSend",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      IMultichainPortal.StargateArgsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "beneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastErr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastSrcAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mulDiv", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "portalRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sgReceive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stargateRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapERC20AndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapERC20AndSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapNativeAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapNativeAndSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "SwapCallError(string)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapCallError"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface SwapCallErrorEventObject {
  reason: string;
}
export type SwapCallErrorEvent = TypedEvent<[string], SwapCallErrorEventObject>;

export type SwapCallErrorEventFilter = TypedEventFilter<SwapCallErrorEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface MultichainPortal extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MultichainPortalInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    beneficiary(overrides?: CallOverrides): Promise<[string]>;

    fee(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      _portalRouter: PromiseOrValue<string>,
      _stargateRouter: PromiseOrValue<string>,
      _beneficiary: PromiseOrValue<string>,
      _usdc: PromiseOrValue<string>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    lastChainId(overrides?: CallOverrides): Promise<[number]>;

    lastErr(overrides?: CallOverrides): Promise<[string]>;

    lastNonce(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastSrcAddress(overrides?: CallOverrides): Promise<[string]>;

    mulDiv(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      z: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    portalRouter(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    send(
      qty: PromiseOrValue<BigNumberish>,
      dstChainId: PromiseOrValue<BigNumberish>,
      srcPoolId: PromiseOrValue<BigNumberish>,
      dstPoolId: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      lzTxObj: IStargateRouter.LzTxObjStruct,
      receiver: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sgReceive(
      _chainId: PromiseOrValue<BigNumberish>,
      _srcAddress: PromiseOrValue<BytesLike>,
      _nonce: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      amountLD: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stargateRouter(overrides?: CallOverrides): Promise<[string]>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    swapERC20AndCall(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      calls: Types.ICallStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapERC20AndSend(
      amountIn: PromiseOrValue<BigNumberish>,
      amountUSDC: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      stargateArgs: IMultichainPortal.StargateArgsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapNativeAndCall(
      tokenOut: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      calls: Types.ICallStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapNativeAndSend(
      amountIn: PromiseOrValue<BigNumberish>,
      amountUSDC: PromiseOrValue<BigNumberish>,
      lzFee: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      stargateArgs: IMultichainPortal.StargateArgsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    usdc(overrides?: CallOverrides): Promise<[string]>;
  };

  beneficiary(overrides?: CallOverrides): Promise<string>;

  fee(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    _portalRouter: PromiseOrValue<string>,
    _stargateRouter: PromiseOrValue<string>,
    _beneficiary: PromiseOrValue<string>,
    _usdc: PromiseOrValue<string>,
    _fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  lastChainId(overrides?: CallOverrides): Promise<number>;

  lastErr(overrides?: CallOverrides): Promise<string>;

  lastNonce(overrides?: CallOverrides): Promise<BigNumber>;

  lastSrcAddress(overrides?: CallOverrides): Promise<string>;

  mulDiv(
    x: PromiseOrValue<BigNumberish>,
    y: PromiseOrValue<BigNumberish>,
    z: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  onERC1155BatchReceived(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>[],
    arg3: PromiseOrValue<BigNumberish>[],
    arg4: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  onERC1155Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BigNumberish>,
    arg4: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  portalRouter(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  send(
    qty: PromiseOrValue<BigNumberish>,
    dstChainId: PromiseOrValue<BigNumberish>,
    srcPoolId: PromiseOrValue<BigNumberish>,
    dstPoolId: PromiseOrValue<BigNumberish>,
    minAmountOut: PromiseOrValue<BigNumberish>,
    lzTxObj: IStargateRouter.LzTxObjStruct,
    receiver: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sgReceive(
    _chainId: PromiseOrValue<BigNumberish>,
    _srcAddress: PromiseOrValue<BytesLike>,
    _nonce: PromiseOrValue<BigNumberish>,
    _token: PromiseOrValue<string>,
    amountLD: PromiseOrValue<BigNumberish>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stargateRouter(overrides?: CallOverrides): Promise<string>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  swapERC20AndCall(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    user: PromiseOrValue<string>,
    swapRouter: PromiseOrValue<string>,
    swapArguments: PromiseOrValue<BytesLike>,
    calls: Types.ICallStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapERC20AndSend(
    amountIn: PromiseOrValue<BigNumberish>,
    amountUSDC: PromiseOrValue<BigNumberish>,
    user: PromiseOrValue<string>,
    tokenIn: PromiseOrValue<string>,
    swapRouter: PromiseOrValue<string>,
    swapArguments: PromiseOrValue<BytesLike>,
    stargateArgs: IMultichainPortal.StargateArgsStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapNativeAndCall(
    tokenOut: PromiseOrValue<string>,
    user: PromiseOrValue<string>,
    swapRouter: PromiseOrValue<string>,
    swapArguments: PromiseOrValue<BytesLike>,
    calls: Types.ICallStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapNativeAndSend(
    amountIn: PromiseOrValue<BigNumberish>,
    amountUSDC: PromiseOrValue<BigNumberish>,
    lzFee: PromiseOrValue<BigNumberish>,
    user: PromiseOrValue<string>,
    swapRouter: PromiseOrValue<string>,
    swapArguments: PromiseOrValue<BytesLike>,
    stargateArgs: IMultichainPortal.StargateArgsStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  usdc(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    beneficiary(overrides?: CallOverrides): Promise<string>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _portalRouter: PromiseOrValue<string>,
      _stargateRouter: PromiseOrValue<string>,
      _beneficiary: PromiseOrValue<string>,
      _usdc: PromiseOrValue<string>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    lastChainId(overrides?: CallOverrides): Promise<number>;

    lastErr(overrides?: CallOverrides): Promise<string>;

    lastNonce(overrides?: CallOverrides): Promise<BigNumber>;

    lastSrcAddress(overrides?: CallOverrides): Promise<string>;

    mulDiv(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      z: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    portalRouter(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    send(
      qty: PromiseOrValue<BigNumberish>,
      dstChainId: PromiseOrValue<BigNumberish>,
      srcPoolId: PromiseOrValue<BigNumberish>,
      dstPoolId: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      lzTxObj: IStargateRouter.LzTxObjStruct,
      receiver: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    sgReceive(
      _chainId: PromiseOrValue<BigNumberish>,
      _srcAddress: PromiseOrValue<BytesLike>,
      _nonce: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      amountLD: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    stargateRouter(overrides?: CallOverrides): Promise<string>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    swapERC20AndCall(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      calls: Types.ICallStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    swapERC20AndSend(
      amountIn: PromiseOrValue<BigNumberish>,
      amountUSDC: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      stargateArgs: IMultichainPortal.StargateArgsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    swapNativeAndCall(
      tokenOut: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      calls: Types.ICallStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    swapNativeAndSend(
      amountIn: PromiseOrValue<BigNumberish>,
      amountUSDC: PromiseOrValue<BigNumberish>,
      lzFee: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      stargateArgs: IMultichainPortal.StargateArgsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    usdc(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "SwapCallError(string)"(reason?: null): SwapCallErrorEventFilter;
    SwapCallError(reason?: null): SwapCallErrorEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    beneficiary(overrides?: CallOverrides): Promise<BigNumber>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _portalRouter: PromiseOrValue<string>,
      _stargateRouter: PromiseOrValue<string>,
      _beneficiary: PromiseOrValue<string>,
      _usdc: PromiseOrValue<string>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    lastChainId(overrides?: CallOverrides): Promise<BigNumber>;

    lastErr(overrides?: CallOverrides): Promise<BigNumber>;

    lastNonce(overrides?: CallOverrides): Promise<BigNumber>;

    lastSrcAddress(overrides?: CallOverrides): Promise<BigNumber>;

    mulDiv(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      z: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    portalRouter(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    send(
      qty: PromiseOrValue<BigNumberish>,
      dstChainId: PromiseOrValue<BigNumberish>,
      srcPoolId: PromiseOrValue<BigNumberish>,
      dstPoolId: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      lzTxObj: IStargateRouter.LzTxObjStruct,
      receiver: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sgReceive(
      _chainId: PromiseOrValue<BigNumberish>,
      _srcAddress: PromiseOrValue<BytesLike>,
      _nonce: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      amountLD: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stargateRouter(overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapERC20AndCall(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      calls: Types.ICallStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapERC20AndSend(
      amountIn: PromiseOrValue<BigNumberish>,
      amountUSDC: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      stargateArgs: IMultichainPortal.StargateArgsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapNativeAndCall(
      tokenOut: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      calls: Types.ICallStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapNativeAndSend(
      amountIn: PromiseOrValue<BigNumberish>,
      amountUSDC: PromiseOrValue<BigNumberish>,
      lzFee: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      stargateArgs: IMultichainPortal.StargateArgsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    usdc(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    beneficiary(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _portalRouter: PromiseOrValue<string>,
      _stargateRouter: PromiseOrValue<string>,
      _beneficiary: PromiseOrValue<string>,
      _usdc: PromiseOrValue<string>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    lastChainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastErr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastNonce(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastSrcAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mulDiv(
      x: PromiseOrValue<BigNumberish>,
      y: PromiseOrValue<BigNumberish>,
      z: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>[],
      arg3: PromiseOrValue<BigNumberish>[],
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BigNumberish>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    portalRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    send(
      qty: PromiseOrValue<BigNumberish>,
      dstChainId: PromiseOrValue<BigNumberish>,
      srcPoolId: PromiseOrValue<BigNumberish>,
      dstPoolId: PromiseOrValue<BigNumberish>,
      minAmountOut: PromiseOrValue<BigNumberish>,
      lzTxObj: IStargateRouter.LzTxObjStruct,
      receiver: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sgReceive(
      _chainId: PromiseOrValue<BigNumberish>,
      _srcAddress: PromiseOrValue<BytesLike>,
      _nonce: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      amountLD: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stargateRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapERC20AndCall(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      calls: Types.ICallStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapERC20AndSend(
      amountIn: PromiseOrValue<BigNumberish>,
      amountUSDC: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      stargateArgs: IMultichainPortal.StargateArgsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapNativeAndCall(
      tokenOut: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      calls: Types.ICallStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapNativeAndSend(
      amountIn: PromiseOrValue<BigNumberish>,
      amountUSDC: PromiseOrValue<BigNumberish>,
      lzFee: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      swapRouter: PromiseOrValue<string>,
      swapArguments: PromiseOrValue<BytesLike>,
      stargateArgs: IMultichainPortal.StargateArgsStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    usdc(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
