/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CryptoPunks2Minter } from "./CryptoPunks2Minter";
export type { IERC721Delegate } from "./IERC721Delegate";
