/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as cryptoPunksDelegateSol from "./CryptoPunksDelegate.sol";
export { IPunks2__factory } from "./IPunks2__factory";
