/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as atk from "./ATK";
export type { atk };
import type * as cryptoPunks2 from "./CryptoPunks2";
export type { cryptoPunks2 };
import type * as hootles from "./Hootles";
export type { hootles };
