/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ATKLandMinter } from "./ATKLandMinter";
export type { IERC721Delegate } from "./IERC721Delegate";
