/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as atkDelegateSol from "./ATKDelegate.sol";
export type { atkDelegateSol };
export type { IATKLand } from "./IATKLand";
