/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cryptoPunksDelegateSol from "./CryptoPunksDelegate.sol";
export type { cryptoPunksDelegateSol };
export type { IPunks2 } from "./IPunks2";
